### ISSUE TITLE
Remove (personal) #Include ... UserCommands

### ISSUE THREAD

**Issue by OvercastBTC** [bjagasia/public-ahk-shadowblade#1]
In GUI.ahk, there is a link to a personal UserCommands that does not exist:

#Include %A_ScriptDir%\GUI\UserCommands_bjagasiaPersonal.ahk

Remove/Comment out

**Comment by bjagasia** [comment]
Thank you  @OvercastBTC - good catch. Latest push has commented out the line with some guidance as well.

**Comment by OvercastBTC** [comment]
No problem. I'm working on converting this to v2 (first), and making some (minor) modifications like expanding the GUI size a little to display the results of "?" (I added /help to do the same thing) in the gui, with the goal to have it update like intellisense, and such.
